/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}", 
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "./index.html"
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ['"Outfit"', 'sans-serif'],
        body: ['"Outfit"', 'sans-serif'],
        'impact-lg': ['"Space Grotesk"', 'sans-serif'],
        'eyebrow': ['"Space Grotesk"', 'sans-serif'],
        'body-main': ['"Inter"', 'sans-serif'],
        'mono-label': ['"Space Grotesk"', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent-shadcn))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        cosmic: {
          DEFAULT: "#a855f7",
          tint: "#9333ea",
          deep: "#7c3aed",
          low: "rgba(168, 85, 247, 0.1)",
          glow: "rgba(168, 85, 247, 0.25)",
        },
        // AuraMind Design System Colors
        surface: '#0d1515',
        'surface-dim': '#0d1515',
        'surface-bright': '#333b3b',
        'surface-container-lowest': '#080f10',
        'surface-container-low': '#151d1e',
        'surface-container': '#192122',
        'surface-container-high': '#232b2c',
        'surface-container-highest': '#2e3637',
        'on-surface': '#dce4e5',
        'on-surface-variant': '#b9cacb',
        'inverse-surface': '#dce4e5',
        'inverse-on-surface': '#2a3233',
        outline: '#849495',
        'outline-variant': '#3b494b',
        'surface-tint': '#8B5CF6',
        primary: '#F5F3FF',
        'on-primary': '#4B0082',
        'primary-container': '#EDE9FE',
        'on-primary-container': '#6D28D9',
        'inverse-primary': '#6D28D9',
        secondary: '#d0bcff',
        'on-secondary': '#3c0091',
        'secondary-container': '#571bc1',
        'on-secondary-container': '#c4abff',
        tertiary: '#fff3f2',
        'on-tertiary': '#67001b',
        'tertiary-container': '#ffcdcf',
        'on-tertiary-container': '#bc0b3b',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#C4B5FD',
        'primary-fixed-dim': '#8B5CF6',
        'on-primary-fixed': '#2E1A47',
        'on-primary-fixed-variant': '#5D3FD3',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d0bcff',
        'on-secondary-fixed': '#23005c',
        'on-secondary-fixed-variant': '#5516be',
        'tertiary-fixed': '#ffdadb',
        'tertiary-fixed-dim': '#ffb2b7',
        'on-tertiary-fixed': '#40000d',
        'on-tertiary-fixed-variant': '#92002a',
        'bg-neural': '#050505',
        'surface-glass': 'rgba(15, 15, 20, 0.7)',
        'border-brutal': '#262626',
        'accent-neural-grid': '#121212',
        'status-retention-high': '#8B5CF6',
        'status-retention-low': '#A78BFA',
      },
      fontSize: {
        'impact-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-main': ['16px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'mono-label': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'eyebrow': ['12px', { lineHeight: '1.2', letterSpacing: '0.2em', fontWeight: '600' }],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        DEFAULT: "0.125rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        'sidebar-width': '280px',
        'container-max': '1440px',
        'card-padding': '20px',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
}
