import React, { useState } from 'react';
import { auraAiClient, STUDY_AGENT_SYSTEM_PROMPT } from '../services/auraAiService';
import { ChevronLeft, Bot, Music, X } from 'lucide-react';
import { StudyToolAction, ChatMessage, Quiz, FlashcardData, Deck, Card } from '../types';
import ChatQuiz from './ChatQuiz';
import ChatFlashcardPreview from './ChatFlashcardPreview';
import PresentationViewer from './PresentationViewer';
import { getInitialCardState } from '../services/srs';

interface Message {
  role: 'user' | 'assistant';
  content: string;
}

interface AuraChatProps {
  onBack?: () => void;
  onCreateDeck?: (deck: Omit<Deck, 'id' | 'createdAt' | 'cardCount'>) => void;
  onCreateCard?: (card: Omit<Card, 'id'>) => void;
}

const AuraChat: React.FC<AuraChatProps> = ({ onBack, onCreateDeck, onCreateCard }) => {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const parseToolAction = (content: string): StudyToolAction | null => {
    try {
      // Look for JSON pattern, potentially inside markdown code blocks
      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const jsonStr = jsonMatch[0];
        const parsed = JSON.parse(jsonStr);
        if (parsed.tool && (parsed.data || parsed.cards)) {
          // Flatten data/cards structure if needed to match StudyToolAction
          return {
            tool: parsed.tool,
            data: parsed.data || { cards: parsed.cards }
          } as StudyToolAction;
        }
      }
    } catch (e) {
      // Not a valid JSON, return null
    }
    return null;
  };

  const getCleanContent = (content: string): string => {
    // 1. Remove markdown code blocks (especially json ones)
    let cleaned = content.replace(/```[a-z]*\n?[\s\S]*?```/g, '');

    // 2. Remove JSON-like structures that might be at the end or middle
    // Look for the largest block starting with { and ending with }
    const firstBrace = cleaned.indexOf('{');
    const lastBrace = cleaned.lastIndexOf('}');

    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
      // Check if it looks like one of our tools
      const potentialJson = cleaned.substring(firstBrace, lastBrace + 1);
      if (potentialJson.includes('"tool":') || potentialJson.includes('"questions":') || potentialJson.includes('"cards":')) {
        cleaned = cleaned.substring(0, firstBrace) + cleaned.substring(lastBrace + 1);
      }
    }

    // 3. Remove common AI "filler" phrases that appear when it's about to show a tool
    const fillers = [
      /I have generated [\s\S]*? for you:?/gi,
      /Certainly! Here is [\s\S]*?:/gi,
      /Sure, I can help with that\.?[\s\S]*?:/gi,
      /Here is the [\s\S]*? you requested:?/gi,
      /\[TOOL: [\s\S]*?\]/gi,
      /`tool`:[\s\S]*?/gi
    ];

    fillers.forEach(regex => {
      cleaned = cleaned.replace(regex, '');
    });

    return cleaned.trim();
  };

  const handleQuizComplete = (score: number, total: number) => {
    const completionMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: 'assistant',
      content: `🎉 Quiz completed! You scored ${score} out of ${total} (${Math.round((score / total) * 100)}%). Keep up the great work!`,
      timestamp: Date.now()
    };
    setMessages(prev => [...prev, completionMessage]);
  };

  const handleSaveFlashcards = (cards: FlashcardData[], deckTitle: string) => {
    if (!onCreateDeck || !onCreateCard) return;

    // Create the deck first
    const newDeck = {
      title: deckTitle,
      description: `Deck with ${cards.length} flashcard${cards.length !== 1 ? 's' : ''} generated by Study Agent`,
      cardCount: cards.length
    };
    onCreateDeck(newDeck);

    // Create cards for the deck (in a real app, we'd need the deck ID)
    cards.forEach((cardData, index) => {
      // Note: This is a simplified version. In a real implementation, 
      // you'd need the actual deck ID from the created deck
      setTimeout(() => {
        const newCard = getInitialCardState('temp-deck-id', cardData.question, cardData.answer);
        onCreateCard(newCard);
      }, index * 100); // Small delay to avoid overwhelming
    });

    const successMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: 'assistant',
      content: `✅ Successfully saved ${cards.length} flashcard${cards.length !== 1 ? 's' : ''} to deck "${deckTitle}"! You can now study them using the spaced repetition system.`,
      timestamp: Date.now()
    };
    setMessages(prev => [...prev, successMessage]);
  };

  const handleSendMessage = async () => {
    if (!input.trim()) return;

    const userMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: 'user',
      content: input,
      timestamp: Date.now()
    };
    setMessages(prev => [...prev, userMessage]);

    const assistantId = crypto.randomUUID();
    const assistantMessage: ChatMessage = {
      id: assistantId,
      role: 'assistant',
      content: '',
      thinking: '',
      timestamp: Date.now()
    };

    setMessages(prev => [...prev, assistantMessage]);
    setInput('');
    setIsLoading(true);
    setError(null);

    let fullContent = '';
    let thinkingContent = '';
    let isThinking = false;

    try {
      const stream = auraAiClient.streamChatCompletion({
        messages: [
          { role: 'system', content: STUDY_AGENT_SYSTEM_PROMPT },
          ...messages.map(m => ({ role: m.role as any, content: m.content })),
          { role: 'user', content: input }
        ]
      });

      for await (const chunk of stream) {
        // Detect <think> tags which are common in reasoning models like DeepSeek-R1
        if (chunk.includes('<think>')) {
          isThinking = true;
          const parts = chunk.split('<think>');
          fullContent += parts[0];
          thinkingContent += parts[1] || '';
        } else if (chunk.includes('</think>')) {
          isThinking = false;
          const parts = chunk.split('</think>');
          thinkingContent += parts[0];
          fullContent += parts[1] || '';
        } else {
          if (isThinking) {
            thinkingContent += chunk;
          } else {
            fullContent += chunk;
          }
        }

        setMessages(prev => prev.map(msg =>
          msg.id === assistantId
            ? { ...msg, content: fullContent, thinking: thinkingContent }
            : msg
        ));
      }

      // Final processing - check for tool actions
      const finalMsg = fullContent;
      const toolAction = parseToolAction(finalMsg);
      if (toolAction) {
        setMessages(prev => prev.map(msg =>
          msg.id === assistantId
            ? { ...msg, toolAction }
            : msg
        ));
      }

    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
      // Remove the empty assistant message if it failed immediately
      setMessages(prev => prev.filter(m => m.id !== assistantId || m.content !== ''));
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const [expandedThinking, setExpandedThinking] = useState<Record<string, boolean>>({});

  const toggleThinking = (id: string) => {
    setExpandedThinking(prev => ({ ...prev, [id]: !prev[id] }));
  };

  return (
    <div className="flex flex-col h-full w-full bg-[#050505] text-white overflow-hidden font-body">
      {/* Premium Header */}
      <div className="flex items-center justify-between px-4 sm:px-8 py-4 border-b border-white/5 bg-black/40 backdrop-blur-xl z-20">
        <div className="flex items-center gap-6">
          {onBack && (
            <button
              onClick={onBack}
              className="group flex items-center gap-2 text-white/50 hover:text-white transition-all"
            >
              <div className="p-2 rounded-full group-hover:bg-white/5 transition-colors">
                <ChevronLeft size={20} />
              </div>
              <span className="text-sm font-medium">Exit Chat</span>
            </button>
          )}
          <div className="h-6 w-[1px] bg-white/10" />
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-purple-600 to-pink-500 p-[1px]">
              <div className="w-full h-full rounded-[7px] bg-black flex items-center justify-center">
                <Bot size={16} className="text-white" />
              </div>
            </div>
            <div>
              <h2 className="text-sm font-bold tracking-tight">AURA <span className="text-[10px] text-purple-400 font-normal ml-1 border border-purple-500/30 px-1.5 rounded-full">STUDY CHAT</span></h2>
              <p className="text-[10px] text-white/40 uppercase tracking-[0.2em] font-bold">Study Help</p>
            </div>
          </div>
        </div>
      </div>

      {/* Main Chat Area */}
      <div className="flex-1 overflow-y-auto relative custom-scrollbar">
        {/* Shimmer Backdrop */}
        <div className="fixed inset-0 pointer-events-none opacity-20 overflow-hidden">
          <div className="absolute -top-[10%] -left-[10%] w-[40%] h-[40%] bg-purple-600/30 blur-[120px] rounded-full animate-float" />
          <div className="absolute top-[40%] -right-[10%] w-[30%] h-[50%] bg-blue-600/20 blur-[100px] rounded-full animate-float" style={{ animationDelay: '-3s' }} />
        </div>

        <div className="max-w-3xl mx-auto py-8 sm:py-12 px-4 sm:px-6">
          {messages.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 animate-fade-in">
              <div className="w-24 h-24 bg-white/5 rounded-3xl flex items-center justify-center mb-8 border border-white/10 shadow-2xl relative group">
                <div className="absolute inset-0 bg-purple-500/20 blur-2xl rounded-full opacity-0 group-hover:opacity-100 transition-opacity" />
                <Bot size={48} className="text-white relative z-10" />
              </div>
              <h3 className="text-3xl font-display font-bold text-gradient mb-4">How can I help you study today?</h3>
              <p className="text-white/40 text-sm max-w-sm text-center leading-relaxed font-medium">
                I can explain complex theories, generate flashcards, or create custom quizzes based on your topics.
              </p>

              <div className="mt-12 grid grid-cols-2 gap-3 w-full max-w-lg">
                {[
                  { label: "Explain Quantum Physics", icon: "⚛️" },
                  { label: "Create Biology Quiz", icon: "🧬" },
                  { label: "Math Flashcards", icon: "🔢" },
                  { label: "History Summary", icon: "📜" }
                ].map((s, i) => (
                  <button
                    key={i}
                    onClick={() => setInput(s.label)}
                    className="glass-card p-4 rounded-xl text-xs font-bold text-white/60 hover:text-white flex items-center gap-3 active:scale-95 text-left"
                  >
                    <span className="text-lg">{s.icon}</span> {s.label}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            <div className="space-y-12 pb-24">
              {messages.map((message, index) => {
                const isToolMessage = message.role === 'assistant' && message.toolAction;
                const hasThinking = message.thinking && message.thinking.trim().length > 0;
                const isThinkingCurrently = isLoading && index === messages.length - 1 && hasThinking;
                const cleanText = getCleanContent(message.content);

                return (
                  <div key={message.id || index} className={`animate-fade-in flex flex-col ${message.role === 'user' ? 'items-end' : 'items-start'}`}>
                    {/* Role Badge */}
                    <div className="flex items-center gap-2 mb-3 px-1">
                      {message.role === 'assistant' ? (
                        <span className="text-[10px] font-bold text-purple-400 uppercase tracking-widest bg-purple-500/10 px-2 py-0.5 rounded-full border border-purple-500/20">AI Helper</span>
                      ) : (
                        <span className="text-[10px] font-bold text-white/30 uppercase tracking-widest">Question</span>
                      )}
                    </div>

                    {/* Thinking Process Dropdown */}
                    {hasThinking && (
                      <div className="mb-4 w-full">
                        <button
                          onClick={() => toggleThinking(message.id!)}
                          className="flex items-center gap-2 text-[10px] uppercase font-bold tracking-tighter text-white/30 hover:text-purple-400 transition-all border-l border-white/10 ml-4 pl-4 py-1 group"
                        >
                          <div className={`transition-transform duration-500 ${expandedThinking[message.id!] ? 'rotate-180' : ''}`}>
                            <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M19 9l-7 7-7-7" /></svg>
                          </div>
                          <span>{isThinkingCurrently ? 'Thinking...' : 'See how it worked this out'}</span>
                          {isThinkingCurrently && (
                            <div className="w-1 h-1 bg-purple-500 rounded-full animate-ping" />
                          )}
                        </button>

                        {expandedThinking[message.id!] && (
                          <div className="mt-2 ml-4 p-5 bg-white/[0.02] border border-white/5 rounded-2xl text-[11px] text-white/40 leading-relaxed italic whitespace-pre-wrap animate-in slide-in-from-top-1 duration-500">
                            {message.thinking}
                          </div>
                        )}
                      </div>
                    )}

                    {/* Message Bubble/Content */}
                    <div
                      className={`relative max-w-[90%] transition-all duration-300 ${message.role === 'user'
                        ? 'bg-gradient-to-br from-purple-600 to-indigo-600 text-white rounded-3xl rounded-tr-none py-3 px-5 shadow-xl'
                        : 'w-full'
                        }`}
                    >
                      {/* Text Content */}
                      {cleanText.length > 0 && (
                        <div className={`text-sm leading-relaxed whitespace-pre-wrap font-medium ${message.role === 'assistant' ? 'text-white/80 border-l border-white/10 pl-6' : ''}`}>
                          {cleanText}
                        </div>
                      )}

                      {/* Tool UI Rendering */}
                      {isToolMessage && message.toolAction && (
                        <div className="mt-8 mb-4 w-full">
                          {message.toolAction.tool === 'generate_quiz' && (
                            <div className="animate-fade-in-up">
                              <ChatQuiz
                                quiz={message.toolAction.data as Quiz}
                                onComplete={handleQuizComplete}
                              />
                            </div>
                          )}
                          {message.toolAction.tool === 'generate_flashcards' && (
                            <div className="animate-fade-in-up">
                              <ChatFlashcardPreview
                                cards={message.toolAction.data.cards as FlashcardData[]}
                                onSaveCards={handleSaveFlashcards}
                              />
                            </div>
                          )}
                          {message.toolAction.tool === 'explain_concept' && (
                            <div className="glass-card rounded-[32px] p-8 border border-white/10 relative overflow-hidden group animate-fade-in-up">
                              <div className="absolute top-0 right-0 w-32 h-32 bg-purple-500/10 blur-3xl -mr-16 -mt-16 group-hover:bg-purple-500/20 transition-all duration-1000" />

                              <div className="flex items-center gap-3 mb-6">
                                <div className="p-2 rounded-xl bg-purple-500/10 text-purple-400">
                                  <Music size={18} />
                                </div>
                                <h4 className="font-display font-bold text-2xl text-gradient uppercase tracking-tight">
                                  {message.toolAction.data.concept}
                                </h4>
                              </div>

                              <div className="text-white/70 text-base leading-loose mb-8 font-medium">
                                {message.toolAction.data.explanation}
                              </div>

                              <div className="grid md:grid-cols-2 gap-8 pt-8 border-t border-white/5">
                                {message.toolAction.data.examples && (
                                  <div className="space-y-4">
                                    <div className="text-[10px] font-bold text-white/30 uppercase tracking-[0.3em]">Examples & Context</div>
                                    <ul className="space-y-3">
                                      {message.toolAction.data.examples.map((example: string, i: number) => (
                                        <li key={i} className="text-sm text-white/60 flex gap-3 items-start">
                                          <span className="w-1 h-1 rounded-full bg-purple-500/40 mt-2 shrink-0"></span> {example}
                                        </li>
                                      ))}
                                    </ul>
                                  </div>
                                )}
                                {message.toolAction.data.keyPoints && (
                                  <div className="space-y-4">
                                    <div className="text-[10px] font-bold text-white/30 uppercase tracking-[0.3em]">Key Points</div>
                                    <ul className="space-y-3">
                                      {message.toolAction.data.keyPoints.map((point: string, i: number) => (
                                        <li key={i} className="text-sm text-white/60 flex gap-3 items-start">
                                          <span className="w-1.5 h-1.5 rounded-full bg-blue-500/40 mt-1.5 shrink-0"></span> {point}
                                        </li>
                                      ))}
                                    </ul>
                                  </div>
                                )}
                              </div>
                            </div>
                          )}
                          {message.toolAction.tool === 'generate_presentation' && (
                            <div className="w-full animate-fade-in-up">
                              <PresentationViewer
                                title={message.toolAction.data.title}
                                slides={message.toolAction.data.slides}
                              />
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          {/* Initial Loading Indicator */}
          {isLoading && !messages[messages.length - 1]?.content && !messages[messages.length - 1]?.thinking && (
            <div className="flex items-center gap-4 animate-fade-in ml-4">
              <div className="flex gap-1.5">
                <div className="w-1.5 h-1.5 bg-purple-500 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
                <div className="w-1.5 h-1.5 bg-purple-500/60 rounded-full animate-bounce [animation-delay:-0.15s]"></div>
                <div className="w-1.5 h-1.5 bg-purple-500/30 rounded-full animate-bounce"></div>
              </div>
              <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/30">Looking through your study info</span>
            </div>
          )}

          {error && (
            <div className="mx-auto max-w-lg mt-8 glass-card border-red-500/20 p-4 rounded-2xl flex items-center gap-4 animate-shake">
              <div className="w-10 h-10 rounded-xl bg-red-500/10 flex items-center justify-center text-red-500">
                <X size={20} />
              </div>
              <div className="flex-1">
                <div className="text-[10px] font-bold text-red-500 uppercase tracking-wider mb-1">Something Went Wrong</div>
                <div className="text-sm text-red-200/60">{error}</div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Premium Input Area */}
      <div className="p-4 sm:p-8 bg-gradient-to-t from-black via-black/80 to-transparent relative z-30">
        <div className="max-w-2xl mx-auto relative group">
          <div className="absolute -inset-[1px] bg-gradient-to-r from-purple-600/20 to-blue-600/20 rounded-[24px] blur-sm opacity-0 group-focus-within:opacity-100 transition-opacity" />
          <div className="relative flex items-center bg-white/[0.03] border border-white/10 rounded-[24px] overflow-hidden backdrop-blur-3xl transition-all group-focus-within:border-white/20 group-focus-within:bg-white/[0.05]">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyPress={handleKeyPress}
              placeholder="Ask for help with a topic..."
              className="w-full p-5 pl-7 bg-transparent focus:outline-none text-white text-sm placeholder:text-white/20 font-medium"
              disabled={isLoading}
            />
            <div className="flex items-center gap-2 pr-4">
              <button
                onClick={handleSendMessage}
                disabled={isLoading || !input.trim()}
                className={`w-10 h-10 rounded-xl flex items-center justify-center transition-all ${isLoading || !input.trim()
                  ? 'bg-white/5 text-white/10'
                  : 'bg-white text-black hover:scale-105 active:scale-95 shadow-xl'
                  }`}
              >
                {isLoading ? (
                  <div className="w-4 h-4 border-2 border-black/20 border-t-black rounded-full animate-spin"></div>
                ) : (
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                  </svg>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>

      <style dangerouslySetInnerHTML={{
        __html: `
        .custom-scrollbar::-webkit-scrollbar { width: 5px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.05); border-radius: 10px; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: rgba(255,255,255,0.1); }
        @keyframes shake {
          0%, 100% { transform: translateX(0); }
          25% { transform: translateX(-5px); }
          75% { transform: translateX(5px); }
        }
        .animate-shake { animation: shake 0.4s ease-in-out; }
      `}} />
    </div>
  );
};

export default AuraChat;
